# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Data(models.Model):
    column1 = models.CharField(db_column='Column1', max_length=50, blank=True, primary_key=True)  # Field name made lowercase.
    air_motor = models.CharField(db_column='AIR_MOTOR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    approved_by = models.CharField(db_column='APPROVED_BY', max_length=4, blank=True, null=True)  # Field name made lowercase.
    chs = models.CharField(db_column='CHS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cust = models.CharField(db_column='CUST', max_length=50, blank=True, null=True)  # Field name made lowercase.
    date_drawn = models.CharField(db_column='DATE_DRAWN', max_length=10, blank=True, null=True)  # Field name made lowercase.
    descr = models.CharField(db_column='DESCR', max_length=50, blank=True, null=True)  # Field name made lowercase.
    dirname = models.CharField(db_column='DIRNAME', max_length=1, blank=True, null=True)  # Field name made lowercase.
    drawing_number = models.CharField(db_column='DRAWING_NUMBER', max_length=50, blank=True)  # Field name made lowercase.
    drawn_by = models.CharField(db_column='DRAWN_BY', max_length=10, blank=True, null=True)  # Field name made lowercase.
    dwg_type = models.CharField(db_column='DWG_TYPE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    elec_motor = models.CharField(db_column='ELEC_MOTOR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em_lockout = models.CharField(db_column='EM_LOCKOUT', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em_sequencing = models.CharField(db_column='EM_SEQUENCING', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em_single_pilot_source = models.CharField(db_column='EM_SINGLE_PILOT_SOURCE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em_fail_open = models.CharField(db_column='EM_FAIL_OPEN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em_low_trip_position = models.CharField(db_column='EM_LOW_TRIP_POSITION', max_length=1, blank=True, null=True)  # Field name made lowercase.
    r = models.CharField(db_column='R', max_length=1, blank=True, null=True)  # Field name made lowercase.
    s = models.CharField(db_column='S', max_length=1, blank=True, null=True)  # Field name made lowercase.
    t = models.CharField(db_column='T', max_length=1, blank=True, null=True)  # Field name made lowercase.
    u = models.CharField(db_column='U', max_length=1, blank=True, null=True)  # Field name made lowercase.
    v = models.CharField(db_column='V', max_length=1, blank=True, null=True)  # Field name made lowercase.
    w = models.CharField(db_column='W', max_length=1, blank=True, null=True)  # Field name made lowercase.
    x = models.CharField(db_column='X', max_length=1, blank=True, null=True)  # Field name made lowercase.
    y = models.CharField(db_column='Y', max_length=1, blank=True, null=True)  # Field name made lowercase.
    z = models.CharField(db_column='Z', max_length=1, blank=True, null=True)  # Field name made lowercase.
    aa = models.CharField(db_column='AA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ab = models.CharField(db_column='AB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ac = models.CharField(db_column='AC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ad = models.CharField(db_column='AD', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ae = models.CharField(db_column='AE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    af = models.CharField(db_column='AF', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ag = models.CharField(db_column='AG', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ah = models.CharField(db_column='AH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ai = models.CharField(db_column='AI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    aj = models.CharField(db_column='AJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ak = models.CharField(db_column='AK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    al = models.CharField(db_column='AL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    am = models.CharField(db_column='AM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    an = models.CharField(db_column='AN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ao = models.CharField(db_column='AO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ap = models.CharField(db_column='AP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    aq = models.CharField(db_column='AQ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ar = models.CharField(db_column='AR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    a_s = models.CharField(db_column='A_S', max_length=1, blank=True, null=True)  # Field name made lowercase.
    a_t = models.CharField(db_column='A_T', max_length=1, blank=True, null=True)  # Field name made lowercase.
    au = models.CharField(db_column='AU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    av = models.CharField(db_column='AV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    aw = models.CharField(db_column='AW', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ax = models.CharField(db_column='AX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ay = models.CharField(db_column='AY', max_length=1, blank=True, null=True)  # Field name made lowercase.
    az = models.CharField(db_column='AZ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ba = models.CharField(db_column='BA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bb = models.CharField(db_column='BB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bc = models.CharField(db_column='BC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bd = models.CharField(db_column='BD', max_length=1, blank=True, null=True)  # Field name made lowercase.
    be = models.CharField(db_column='BE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bf = models.CharField(db_column='BF', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bg = models.CharField(db_column='BG', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bh = models.CharField(db_column='BH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bi = models.CharField(db_column='BI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bj = models.CharField(db_column='BJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bk = models.CharField(db_column='BK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bl = models.CharField(db_column='BL', max_length=20, blank=True, null=True)  # Field name made lowercase.
    bm = models.CharField(db_column='BM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bn = models.CharField(db_column='BN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bo = models.CharField(db_column='BO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bp = models.CharField(db_column='BP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bq = models.CharField(db_column='BQ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    br = models.CharField(db_column='BR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bs = models.CharField(db_column='BS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bt = models.CharField(db_column='BT', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bu = models.CharField(db_column='BU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bv = models.CharField(db_column='BV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bw = models.CharField(db_column='BW', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bx = models.CharField(db_column='BX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    b_y = models.CharField(db_column='B_Y', max_length=1, blank=True, null=True)  # Field name made lowercase.
    bz = models.CharField(db_column='BZ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ca = models.CharField(db_column='CA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cb = models.CharField(db_column='CB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cc = models.CharField(db_column='CC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cd = models.CharField(db_column='CD', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ce = models.CharField(db_column='CE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cf = models.CharField(db_column='CF', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cg = models.CharField(db_column='CG', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ch = models.CharField(db_column='CH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ci = models.CharField(db_column='CI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cj = models.CharField(db_column='CJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ck = models.CharField(db_column='CK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cl = models.CharField(db_column='CL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cm = models.CharField(db_column='CM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cn = models.CharField(db_column='CN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    co = models.CharField(db_column='CO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cp = models.CharField(db_column='CP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cq = models.CharField(db_column='CQ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cr = models.CharField(db_column='CR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cs = models.CharField(db_column='CS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ct = models.CharField(db_column='CT', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cu = models.CharField(db_column='CU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cv = models.CharField(db_column='CV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cw = models.CharField(db_column='CW', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cx = models.CharField(db_column='CX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cy = models.CharField(db_column='CY', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cz = models.CharField(db_column='CZ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    da = models.CharField(db_column='DA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    db = models.CharField(db_column='DB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dc = models.CharField(db_column='DC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dd = models.CharField(db_column='DD', max_length=1, blank=True, null=True)  # Field name made lowercase.
    de = models.CharField(db_column='DE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    df = models.CharField(db_column='DF', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dg = models.CharField(db_column='DG', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dh = models.CharField(db_column='DH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    di = models.CharField(db_column='DI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dj = models.CharField(db_column='DJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dk = models.CharField(db_column='DK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dl = models.CharField(db_column='DL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dm = models.CharField(db_column='DM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dn = models.CharField(db_column='DN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    do = models.CharField(db_column='DO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dp = models.CharField(db_column='DP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dq = models.CharField(db_column='DQ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dr = models.CharField(db_column='DR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ds = models.CharField(db_column='DS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dt = models.CharField(db_column='DT', max_length=1, blank=True, null=True)  # Field name made lowercase.
    du = models.CharField(db_column='DU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dv = models.CharField(db_column='DV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dw = models.CharField(db_column='DW', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dx = models.CharField(db_column='DX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dy = models.CharField(db_column='DY', max_length=1, blank=True, null=True)  # Field name made lowercase.
    dz = models.CharField(db_column='DZ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ea = models.CharField(db_column='EA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    eb = models.CharField(db_column='EB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    e_c = models.CharField(db_column='E_C', max_length=1, blank=True, null=True)  # Field name made lowercase.
    e_d = models.CharField(db_column='E_D', max_length=1, blank=True, null=True)  # Field name made lowercase.
    e_e = models.CharField(db_column='E_E', max_length=20, blank=True, null=True)  # Field name made lowercase.
    e_f = models.CharField(db_column='E_F', max_length=50, blank=True, null=True)  # Field name made lowercase.
    e_g = models.CharField(db_column='E_G', max_length=1, blank=True, null=True)  # Field name made lowercase.
    eh = models.CharField(db_column='EH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ei = models.CharField(db_column='EI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ej = models.CharField(db_column='EJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ek = models.CharField(db_column='EK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    el = models.CharField(db_column='EL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    em = models.CharField(db_column='EM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    en = models.CharField(db_column='EN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    eo = models.CharField(db_column='EO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ep = models.CharField(db_column='EP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    eq = models.CharField(db_column='EQ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    er = models.CharField(db_column='ER', max_length=1, blank=True, null=True)  # Field name made lowercase.
    es = models.CharField(db_column='ES', max_length=1, blank=True, null=True)  # Field name made lowercase.
    et = models.CharField(db_column='ET', max_length=1, blank=True, null=True)  # Field name made lowercase.
    eu = models.CharField(db_column='EU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ev = models.CharField(db_column='EV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ew = models.CharField(db_column='EW', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ex = models.CharField(db_column='EX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ey = models.CharField(db_column='EY', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ez = models.CharField(db_column='EZ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fa = models.CharField(db_column='FA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fb = models.CharField(db_column='FB', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fc = models.CharField(db_column='FC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fd = models.CharField(db_column='FD', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fe = models.CharField(db_column='FE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ff = models.CharField(db_column='FF', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fg = models.CharField(db_column='FG', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fh = models.CharField(db_column='FH', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fi = models.CharField(db_column='FI', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fj = models.CharField(db_column='FJ', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fk = models.CharField(db_column='FK', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fl = models.CharField(db_column='FL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fm = models.CharField(db_column='FM', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fn = models.CharField(db_column='FN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fo = models.CharField(db_column='FO', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fp = models.CharField(db_column='FP', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fq = models.CharField(db_column='FQ', max_length=20, blank=True, null=True)  # Field name made lowercase.
    fr = models.CharField(db_column='FR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fs = models.CharField(db_column='FS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ft = models.CharField(db_column='FT', max_length=4, blank=True, null=True)  # Field name made lowercase.
    fu = models.CharField(db_column='FU', max_length=1, blank=True, null=True)  # Field name made lowercase.
    fv = models.CharField(db_column='FV', max_length=4, blank=True, null=True)  # Field name made lowercase.
    fw = models.CharField(db_column='FW', max_length=90, blank=True, null=True)  # Field name made lowercase.
    fx = models.CharField(db_column='FX', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fy = models.CharField(db_column='FY', max_length=1, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'Data'

